# tasks file for rsync-sync
---
- name: install dependencies
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  with_items: "{{ rsync_sync_dependencies }}"
  tags:
    - configuration
    - rsync-sync
    - rsync-sync-dependencies

- name: generate script(s)
  template:
    src: usr/local/bin/rsync-sync.j2
    dest: "{{ rsync_sync_install_path }}/{{ item.key }}"
    owner: root
    group: root
    mode: 0755
    validate: '/usr/bin/env bash -n %s'
  with_dict: "{{ rsync_sync_scripts }}"
  tags:
    - configuration
    - rsync-sync
    - rsync-sync-configuration

- name: configure (cron) jobs
  cron:
    name: "{{ item.name }}"
    job: "{{ item.job }}"
    state: "{{ item.state | default('present') }}"
    day: "{{ item.day | default('*') }}"
    hour: "{{ item.hour | default('*') }}"
    minute: "{{ item.minute | default('*') }}"
    month: "{{ item.month | default('*') }}"
    weekday: "{{ item.weekday | default('*') }}"
    cron_file: rsync-sync
    user: root
  with_items: "{{ rsync_sync_jobs }}"
  tags:
    - configuration
    - rsync-sync
    - rsync-sync-jobs
